[theme]

# Primary accent for interactive elements
primaryColor = '#6F4E37'  # Café oscuro

# Background color for the main content area
backgroundColor = '#FFF2E1'  # Beige claro

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#AF8F6F' # Beige más claro

# Color used for almost all text
textColor = '#3E2723'  # Marrón oscuro

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "serif"
